export {
  shithead_definition,
  clone_state,
  type Shithead_state,
  type Shithead_player_state,
  type Shithead_command,
  type Shithead_config,
  type Visible_shithead_state,
  type Visible_player_state,
  type Visible_own_player_state,
  DEFAULT_SHITHEAD_CONFIG,
  compute_bot_commands,
  compute_bot_commands_for_difficulty,
  compute_swap_commands,
  compute_play_command,
  is_bot_player,
  ismcts_compute_command,
  MEDIUM_CONFIG,
  HARD_CONFIG,
  type Ismcts_config,
} from './shithead'
